### ISSUE TITLE
Why does VGG-Face end with convolutional layers instead of Dense/Fully-Connected layers?

### ISSUE THREAD

**Issue by FaaizMemonPurdue** [serengil/deepface#1161]
:question:

**Comment by serengil** [comment]
why not? it is an architectural design question. you may ask this to its creators.

**Comment by FaaizMemonPurdue** [comment]
It is an architectural design question, but you answered it differently than the creators, who made the last few layers fully connected, rather than convolutional. This is the most common practice, but I saw that you had put those layers through several commits of tuning for performance, so I wanted to know your reasoning.

**Comment by serengil** [comment]
No, i did not do anything. Original model has convolution layers instead of dense layer.

If you put dense layer, then number of weights will increase dramatically. Using conv decreases complexity and time.

**Comment by serengil** [comment]
From the course notes of Andrew Ng, 

"For example, a 1000x1000 image will represent 3 million feature/input to the full connected neural network. If the following hidden layer contains 1000, then we will want to learn weights of the shape [1000, 3 million] which is 3 billion parameter only in the first layer and thats so computationally expensive! One of the solutions is to build this using convolution layers instead of the fully connected layers."

Ref: https://github.com/ashishpatel26/Andrew-NG-Notes/blob/master/andrewng-p-4-convolutional-neural-network.md
