### ISSUE TITLE
[FEATURE]: New feature integration in api

### ISSUE THREAD

**Issue by Naman5458** [serengil/deepface#1338]
### Description

Hello serengil i hope you are doing fine you have done a pretty good job till now actually i was interested in finding functionality of  deepface which can be accessed by running api service so i made the modification in routes and services file as well for accessing the find functionality but i am facing the issue of 404 not found when i am hitting the endpoint

**Comment by serengil** [comment]
Find function wasn't added to api intent-fully. Because api should be stateless and you should not store facial database in file system. We are even running it with docker.

In future releases, we may add add to db, update and delete methods to store items in external db(s) but find function will not definitely be added to api as is.

**Comment by Naman5458** [comment]
so i am not storing the database in the system, but as we are using laravel for our project we put are facial database over server from where we can access the images of known faces and put it and for which i was modifying the route and services in my local but its not working so it would be very helpfull if you can provide a guide or tips to modify the api a bit in our local

thanks for understandinig
