### ISSUE TITLE
[Question]: ideal config for surveillance face detection and recognition

### ISSUE THREAD

**Issue by almirb** [serengil/deepface#1348]
### Description

Hello!
I know that Stack Overflow would be the right place for asking questions about deepface, but things asked here can answer a lot of people.
@serengil One scenario of detecting/recognizing people faces, is in surveillance video cameras.
I'm trying to do that, but there were some obstacles I need elucidation (if possible):

1. In your opinion: what is the best config for detecing/recognizing/distance method to deal with faces on video captured by surveillance cameras? Retinaface is not viable because It's too much expensive (cpu power).
2. The "wide" angle lenses of these cameras can influenciate on detection results? I'm doing testing with [this camera](https://backend.intelbras.com/sites/default/files/2023-08/Datasheet%20VIP%203830%20B%20V3.pdf). What to do to overcome the lenses aperture effect? And what the minimum face size on image for correct embedding creation?  That would drive what overall camera quality setting I would use.
3. When detecting unknown people, It's possible to create new "anonym profiles" based on these images, to recongize these same persons later, or this is not valid because of the confidence of embedings created for these images?
4. Can I set a more reliable threshold for saving unknown profiles?  Sometimes I get some occluded images and I want to not consider them.  The images needed to be more "frontal" and clean. 
5. I'm using PostgreSQL + Pgvector.  How can I configure with kind of distance measure will be used (euclidean, l2, etc)? I need to set this on table vector index creation?

In my tests, I imported a dataset with more than 1000 faces.  I put a face of mine toghether in this collection, but sometimes I'm recognized as other people.. :(  -  using yunet + facenet + postgres pgvector with cosine distance.

It would be great if you could answer at least some of my questions. 🙏 

Your work putting toghether all this nice detection and recognition frameworks/tools is amazing!
Thanks a lot!  👍

**Comment by serengil** [comment]
Thank you for your questions. I'll do my best to address each one:

Best configuration for face detection/recognition: You can find the best setup for detection and recognition in the DeepFace benchmarks here: [DeepFace Benchmarks](https://github.com/serengil/deepface/tree/master/benchmarks).

Wide-angle lenses and detection: I don't have direct experience with wide-angle lenses, but they can affect the detection accuracy due to distortion. You might need to experiment with different models and settings to see what works best in your case.

Creating anonymous profiles for future recognition: Yes, it's definitely possible to create anonymous profiles from unknown faces and use them for recognition later.

Setting a custom threshold for profile creation: Instead of using the default "verified" result from the verify function, you can use the distance metric in the result and set your own custom threshold to filter out lower-quality or occluded images.

Distance measures in PostgreSQL + Pgvector: For questions related to Pgvector and setting distance measures (e.g., Euclidean, L2, etc.), I recommend checking the Pgvector repository. In my experiments, I used Euclidean distance. Here's a guide that might help: [PostgreSQL as a Vector Database](https://sefiks.com/2024/07/05/postgres-as-a-vector-database-billion-scale-vector-similarity-search-with-pgvector/).

I hope this helps! Feel free to reach out with any more questions.

Thanks again for your kind words and support!
