### ISSUE TITLE
Licence of vggface

### ISSUE THREAD

**Issue by mahamatnoumai** [serengil/deepface#136]
Licensed under Creative Commons: By Attribution 3.0 License.
<img width="664" alt="Screenshot 2020-12-01 at 3 08 12 PM" src="https://user-images.githubusercontent.com/17758399/100708311-0c320a00-33e7-11eb-8a8d-59e5c51cdb49.png">

Hi @serengil I would like to know if **vgg_face** can be use for commercial purpose or not, am kinda confuse about the licensing. could you please further clarify for me if it is okay to use for commercial usages. Thanks appreciate your hard work. keep it up bro.

**Comment by serengil** [comment]
deepface logo is licensed under creative commons. 

to get informed about the license of vgg, please read the disclaimer section.

_Reference face recognition models have different type of licenses. This framework is just a wrapper for those models. That's why, licence types are inherited as well. You should check the licenses for the face recognition models before use.

VGG-Face is licensed under Creative Commons Attribution License. That's why, it is restricted to adopt VGG-Face for commercial use._

**Comment by mahamatnoumai** [comment]
alright thanks for quick reply. really appreciate it. I also came across this. https://www.robots.ox.ac.uk/~vgg/software/vgg_face/ 
<img width="796" alt="Screenshot 2020-12-01 at 3 20 46 PM" src="https://user-images.githubusercontent.com/17758399/100711546-65e90300-33ec-11eb-8f61-6aef55120661.png">
