### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TheHonestBob** [serengil/deepface#1365]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/deepface/issues) and [closed issues](https://github.com/serengil/deepface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### DeepFace's version

v0.0.93

### Python version

3.9.19

### Operating System

ubuntu 22

### Dependencies

tensorflow-gpu==2.7.0
keras==3.6.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2

### Reproducible example

```Python
face_embedding = DeepFace.represent(
                img_path=os.path.join(db_data_dir, each_path),
                model_name='Facenet512',
                detector_backend='yolov8'
            )
```

### Relevant Log Output

Segmentation fault (core dumped)

### Expected Result

when detector_backend=='yolov8' happen Segmentation fault (core dumped), other is ok, DeepFace.find use 'yolov8' is ok

**Comment by serengil** [comment]
You should raise this issue in tensorflow's repo, it is all about it instead of deepface.

**Comment by tristanflechard** [comment]
Hello, 

Using faulthandler, the crash was traced back to psycopg/connection.py. It is caused by a SSL library conflict, psycopg (v2) relies on the C-engine libpq, which attempts to load the system's OpenSSL for the connection handshake, colliding directly with Conda's internal OpenSSL version.

Workarounds:

- Disable SSL (Best for localhost): Append ?sslmode=disable to the end of the DEEPFACE_POSTGRES_URI environment variable.

Hope this help
