### ISSUE TITLE
[FEATURE]: align_img_wrt_eyes performance improvement

### ISSUE THREAD

**Issue by sinopec** [serengil/deepface#1406]
### Description

When I use extract_faces  with align set to be True by default, I found it really slow  for the whole process,
It takes about 1.45 secs while the input img is  2100x1275 with 2 people in  and the detector is yolov8.

I track the whole process and found :
yolov8  cost  0.03 secs
align_img_wrt_eyes  cost about 0.7*2 secs —— two people
What should I do if I want speed up 

use smaller  input image will sure speed up, but  can I do more?
If I turned off align flag ,what will happen?

**Comment by huulockt** [comment]
@serengil Could you please review it and let me know what you think?

**Comment by serengil** [comment]
Would you please run your code for the items in the following issues?

- Issue 1: https://github.com/serengil/deepface/issues/1244
- Issue 2: https://github.com/serengil/retinaface/issues/98

**Comment by huulockt** [comment]
@serengil  tested with **centerface** because there were some problems building **retinaface**. Here are the results (represented as `<face, confidence, (x,y,w,h), right eye coords, left eye coords>`):
### Issue 1:
- ![test1_0](https://github.com/user-attachments/assets/0818466f-afd9-4194-9ed3-970b476e64ae), (1740 301 149 147), 0.907188892364502, (1800, 346), (1849, 380)
- ![test1_1](https://github.com/user-attachments/assets/ecd31e92-f258-4c34-97b3-00f76ab7dabf), (1512 137 152 165), 0.8301119804382324, (1577, 188), (1630, 222)
### Issue 2:
- ![test2_0](https://github.com/user-attachments/assets/8262496c-db1e-448a-a887-c63f34ff6592), (423 240 55 70), 0.9126578569412231, (437, 267), (464, 266)
- ![test2_1](https://github.com/user-attachments/assets/28450543-ec95-44f1-be2f-eaf0552965a3), (187 232 59 70), 0.8854385018348694, (206, 257), (233, 258)
- ![test2_2](https://github.com/user-attachments/assets/3374f9ec-f39d-409b-9011-726cb9eb0fa2), (1 88 47 79), 0.8846514225006104, (7, 113), (36, 113)
- ![test2_3](https://github.com/user-attachments/assets/84405723-0d49-4645-b647-6ba84789ba7d), (523 70 56 76), 0.8671445250511169, (540, 100), (567, 100)

**Comment by serengil** [comment]
@huulockt very good then. would you please create a PR? Your name should appear in the contributors.

If you add an unit test case for 1st bug's item, be appreciate.

**Comment by huulockt** [comment]
@serengil Thank you for the feedback! I’ll create the PR and add the unit test for the first issue as well. I’ll submit it soon!
