### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ptkaster** [serengil/deepface#141]
Hi! Thanks for making such a useful library. 

I'm running into an issue where after running DeepFace.analyze() for Race and Gender there's a memory leak of around 1.3GB. This leak is fixed when the python script ends, but if you call analyze() multiple times in one script it compounds and continues adding on to each other reaching 30+GB of leaked memory depending on how many times you call it. Is this a known issue? 

I know that the README suggests running all of the faces in one call. I'm doing that, but when you then turn this into an API those memory leaks don't escape until the server is rebooted meaning you can only call it a dozen times before getting a memory overload from 30+GB of leaked memory. Thanks for the help!

**Comment by ptkaster** [comment]
Another quirk related to this is that if you exit a script running DeepFace.analyze() before it completes, the memory persists as leaked in the system and you have to manually kill it through Activity Monitor (this is on Mac).

**Comment by serengil** [comment]
If you are going to analyze multiple images, you should not call analyze function in a for loop in the best practice. You can pass inputs as an array. In this way, complex ML models will be built once. Otherwise, if you call analyze in a for loop, then it will build those complex models again and again and this causes memory problems.

`DeepFace.analyze(img_path = ["img1.jpg", "img2.jpg", "img3.jpg"])`

**Comment by Dmitrium12** [comment]
well, what if I still need to constantly call the function over time. Can I somehow free up memory after the function is running?(I'm using a function.find())
