### ISSUE TITLE
Problem in enforce_detection parameter

### ISSUE THREAD

**Issue by thisKK** [serengil/deepface#154]
I try to pass Image has been detect face into Verify function with parameter  enforce_detection = False in model "VGG-Face" not have this problem. But in model  "Facenet",  "OpenFace",  "DeepFace" ,"Ensemble" got returns a wrong value
img1 and img2 is a different person 
![Screenshot 2020-12-23 143737](https://user-images.githubusercontent.com/42506615/102971753-82301980-452c-11eb-9aa1-3d0d5bbc3cf8.png)
```
   img1 = cv2.imread(img_path1)
   img2 = cv2.imread(img_path2)
   detect_face1 = DeepFace.detectFace(img1)
   detect_face2 = DeepFace.detectFace(img2
   obj = DeepFace.verify(detect_face1, detect_face2, model_name= "VGG-Face", enforce_detection=False)
   obj {'distance': 0.5694833993911743,
     'max_threshold_to_verify': 0.4,
     'model': 'VGG-Face',
     'similarity_metric': 'cosine',
     'verified': False}
```
Actually, the result must return false. But in model Facenet, OpenFace got returns a wrong value

```
  obj = DeepFace.verify(detect_face1, detect_face2, model_name= "Facenet", enforce_detection=False)
  obj {'distance': 4.112720489501953e-06,
   'max_threshold_to_verify': 0.4,
   'model': 'Facenet',
   'similarity_metric': 'cosine',
   'verified': True}
```
```
  obj = DeepFace.verify(detect_face1, detect_face2, model_name= "OpenFace",enforce_detection=False) 
  obj {'distance': 0.00014126300811767578,
   'max_threshold_to_verify': 0.1,
   'model': 'OpenFace',
   'similarity_metric': 'cosine',
   'verified': True}
```
But I try to pass with the original Image got a result like this. 
```
  obj = DeepFace.verify(img1, img2, model_name= "Facenet")
  obj {'distance': 0.7559900730848312,
   'max_threshold_to_verify': 0.4,
   'model': 'Facenet',
   'similarity_metric': 'cosine',
   'verified': False} 
```

**Comment by serengil** [comment]
1- setting enforce_detection to False decreases model accuracy dramatically. That's why, its default value is True. If you still want to turn it off, you can run deepface but low accuracy is not surprise.

2- Those models offer high accuracy but it does not guarantee 100% accuracy. That's why, single test results might be wrong.

3- verify function reads image with opencv and it reads BGR format but detectFace function returns RGB format. That's the reason why they act different.
