### ISSUE TITLE
Referenced Error

### ISSUE THREAD

**Issue by akshayshende129** [serengil/deepface#182]
Getting **local variable 'models' referenced before assignment** with below code

```
import os
import itertools
from deepface import DeepFace

vggface_model = DeepFace.build_model("VGG-Face")
openface_model = DeepFace.build_model("OpenFace")
facenet_model = DeepFace.build_model("Facenet")
deepface_model = DeepFace.build_model("DeepFace")

enc_models =  {}
enc_models["VGG-Face"] = vggface_model
enc_models["Facenet"] = facenet_model
enc_models["OpenFace"] = openface_model
enc_models["DeepFace"] = deepface_model

for d in next(os.walk(testDataPath))[1]:
    files = os.listdir(os.path.join(testDataPath,d))
    files = itertools.permutations([os.path.join(testDataPath,d,f) for f in files],2)
    for f1,f2 in list(files):
        print(f1.split("\\")[-1],f2.split("\\")[-1])
        try:
              result = DeepFace.verify(f1,f2, model_name = "Ensemble", model = enc_models)
        except  Exception as e:
              print("Exception: ", e)
              break
    print()

```

**Comment by serengil** [comment]
Please give more details. This exception message comes from where? which module and which line? Exception message should declare that.

**Comment by serengil** [comment]
I found the root cause. I'll fix this in the next release. You can skip this issue if you follow the following steps until the release published.

1- Go to DeepFace.py where it is installed in your environment (Original code here: https://github.com/serengil/deepface/blob/master/deepface/DeepFace.py )

2- Go to 140th line of code

3- Change the command custom_model = models[i] to custom_model = model[i]

That will solve your issue. As I mentioned, I fixed this in the source code. I will publish it in a couple of days. 

Thank you for your contribution.

**Comment by akshayshende129** [comment]
Thank you, this solved my error.
