### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by ALELIWI-Muhammad** [serengil/deepface#205]
Thanks for doing this work, it was useful for me.
1. When I use Dlib model I face this error:
       SystemError: new style getargs format but argument is not a tuple.
2. When I use DeepID model I face this error:
       ValueError: Input 0 is incompatible with layer model_1: expected shape=(None, 55, 47, 3), found shape=(None, 47, 55, 3)

**Solution**: For both of them  modify the line 485  in ../deepface/commons/functions.py
    From:  return input_shape
    To     :  return (input_shape[1],input_shape[0])

**Comment by serengil** [comment]
I updated this in the source code already but I haven't publish it in pip.

You can check it here: https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py 490th line

In my environment, it returns tuple already. That's why, I check it is list or tuple. If it is list, then convert it to tuple.

**Comment by ALELIWI-Muhammad** [comment]
Yes, I used pip install deepface.

There is another error during using DeepID,  would you handle it?
