### ISSUE TITLE
Highly scalable face clustering

### ISSUE THREAD

**Issue by lagmoellertim** [serengil/deepface#213]
Hey, first of all, thanks for your amazing work and written articles on these topics, they helped me out very much 👍 

It seems like you focus a lot on face recognition (match 1 face to the k nearest neighbours), but maybe you have an idea on how to implement efficient face clustering(group faces together or split them apart on conflicting data).

My current stack consists of python and MongoDB, but I'm free to use any tool (currently trying Spark and ElasticSearch). 
Since I want to cluster feature vectors without having all the vectors available (users upload new pictures), and I therefore can not know the total count of different clusters, k-means doesn't work. The only other algos for face clustering I have heard about are Chinese Whispers and DBSCAN, of which none are directly supported by Spark (and ElasticSearch doesn't support clustering at all since it just builds indexes as far as i know). 

Also, just using Nearest Neighbour Search for each new photo and adding it to the cluster the nearest face is in also doesn't work, since clusters could only join this way, but couldn't split apart even if there would be new data which would indicate seperate clusters.

Maybe you have an idea for this problem, if not, or if this is out of scope for this project, feel free to just close this issue, since it's more a question than an issue.

Again, thanks for your work
Cheers 🎉

**Comment by serengil** [comment]
I just studied graph databases for this purpose. Here, you can find my experiments on neo4j.

Tutorial: https://sefiks.com/2021/04/03/deep-face-recognition-with-neo4j/
Video: https://youtu.be/X-hB2kBFBXs

Besides, instead of k-nn, have you ever try approximate nearest neighbors algorithm? Those are the popular a-nn libraries.

Spotify annoy: https://sefiks.com/2020/09/16/large-scale-face-recognition-with-spotify-annoy/
Facebook faiss: https://sefiks.com/2020/09/17/large-scale-face-recognition-with-facebook-faiss/
NMSLIB: https://sefiks.com/2020/09/19/large-scale-face-recognition-with-nmslib/

BTW, Elasticsearch wraps NMSLIB as well: https://sefiks.com/2020/11/27/large-scale-face-recognition-with-elasticsearch/

**Comment by lagmoellertim** [comment]
neo4j is absolutely amazing, I have never heard of a graph db! I will look into it later and see if this will work for my project as well. I am going to try Elasticsearch as well, since I need indecees for other things too (My Project uses OpenAI's Clip, and that produces Feature Vectors as well which need to be indexed). I think we can close this question for now, but maybe it would help other people if you could add the neo4j link to the readme, since clustering faces is usually a big usecase (there are many clustering related questions over a https://github.com/ageitgey/face_recognition)

**Comment by serengil** [comment]
neo4j appears in the read me of this repo actually.

**Comment by lagmoellertim** [comment]
I completely missed that, thanks for pointing it out 👍
