### ISSUE TITLE
Memory leak with DeepFace.find in a loop

### ISSUE THREAD

**Issue by und3f1ned** [serengil/deepface#214]
Thank you for this library!

I need to call DeepFace.find in a loop for realtime face recognition with my camera.
And every frame that I've sent cause memory increase by ~100mb

```python
from deepface import DeepFace

face_req_model = DeepFace.build_model('Dlib')

while True:
    DeepFace.find(img_path=color_frame, db_path='db', model=face_req_model)

```

>find function lasts  1.676849603652954  seconds
>find function lasts  1.7594239711761475  seconds
>find function lasts  1.9610247611999512  seconds
>find function lasts  2.167433500289917  seconds

And so on...
As you can see time also increased.
Please, can you help me? What am I doing wrong?

**Comment by serengil** [comment]
This is very interesting because my experiments show decreasing time in each loop. I had to set model_name in find function otherwise it returns error.

```
model = DeepFace.build_model("Dlib")
print("model built")

for i in range(0, 10):
    DeepFace.find("target.png", db_path = "deepface/tests/dataset"
        , model_name = "Dlib"
        , model = model
    )
```

find function lasts  4.522479772567749  seconds
find function lasts  3.900662899017334  seconds
find function lasts  3.318634033203125  seconds
find function lasts  3.7844293117523193  seconds
find function lasts  2.9691176414489746  seconds
find function lasts  3.1080117225646973  seconds
find function lasts  3.0940170288085938  seconds
find function lasts  3.004420042037964  seconds
find function lasts  2.9620423316955566  seconds
find function lasts  3.457040786743164  seconds

Facenet model experiments are shown below as well.

find function lasts  4.963981628417969  seconds
find function lasts  2.2788169384002686  seconds
find function lasts  1.9085149765014648  seconds
find function lasts  2.178800106048584  seconds
find function lasts  3.4736897945404053  seconds
find function lasts  2.358794927597046  seconds
find function lasts  2.1097145080566406  seconds
find function lasts  2.2929747104644775  seconds
find function lasts  2.0770270824432373  seconds
find function lasts  2.410120964050293  seconds

Spending times in iterations seems stable.

You might try to run garbage collector in each loop.

```
from deepface import DeepFace
import gc
model_name = "Dlib"
model = DeepFace.build_model(model_name)
for i in range(0, 10):
    DeepFace.find("target.png", db_path = "deepface/tests/dataset"
        , model_name = model_name
        , model = model
    )
    gc.collect()
```

**Comment by und3f1ned** [comment]
Garbage collector didn't help. Maybe it's kind of a distro problem (python 3.6.9 ubuntu 18.04) or problem with packages versions. I'll check on another distro and will back later. Thank you!

**Comment by serengil** [comment]
I'm closing this issue but please inform me on this issue.

**Comment by und3f1ned** [comment]
After some investigation I've found the issue.
This is information for those whom may experience such problem.

Bugged build:
`
numpy 1.19.1
pandas 0.23.4
gdown 3.12.2
tqdm 4.59.0
Pillow 6.2.1
opencv-python 4.5.1.48
opencv-contrib-python 4.3.0.36
tensorflow 1.15.0
Keras 2.2.5
Flask 1.1.2
mtcnn 0.1.0
dlib 19.22.0
`

Success build:
`
numpy 1.19.5
pandas 1.1.5
gdown 3.12.2
tqdm 4.60.0
Pillow  8.2.0
opencv-python 4.5.1.48
tensorflow 2.4.1 (!!!)
Keras 2.4.3
Flask 1.1.2
mtcnn 0.1.0
dlib 19.22.0
`

@serengil again, thank you very much for this library. I think that main problem is in tensorflow version, but i'm not sure because i'm just a programmer.

**Comment by serengil** [comment]
thank you for sharing the working environment info.
