### ISSUE TITLE
This is not actually an issue.. this is a request.. 

### ISSUE THREAD

**Issue by sudo-thamaraikannan** [serengil/deepface#22]
shall we can calculate Similarity & Confidence percentage for face verification? if yes, how we can do?

**Comment by serengil** [comment]
Verify function returns distance value. 

If distance is 0, then the both images are same. Different pictures of same person should have a low distance. 

https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py -> findThreshold function returns the maximum threshold values for models. 

You need something different?

I set the status of this issue to closed because this is not an issue.
