### ISSUE TITLE
failed to run api.py with gpu

### ISSUE THREAD

**Issue by flyingmrwang** [serengil/deepface#235]
I am trying to host service for face attribute analysis. To accelerate the inference. I installed tensorflow-gpu==2.5.0 instead of tensorflow. While the inference is still running on CPU, which is pretty slow. When processing request, the cpu usage is high and gpu usage displayed with nvidia-smi is none. Any suggestions? @serengil

**Comment by serengil** [comment]
Running pip install deepface will install regular tensorflow because it is a prerequisite. You should run "pip install deepface --no-deps" to discard the installation of regular tensorflow.

How did you install deepface? 

Please uninstall tensorflow: pip uninstall tensorflow
Install tensorflow gpu: pip install tensorflow-gpu
Install deepface with no dependencies: pip install deepface --no-deps

**Comment by flyingmrwang** [comment]
Thanks for reply. I already fixed this issue. The problem is that i installed tensorflow-gpu without cudnn. As a result, I can succeed import tensorflow but no gpu device was detected. So I installed cudnn and double-check with device_lib.list_local_devices(). Now it is all good!

**Comment by kormoczi** [comment]
I have tried to install tensorflow-gpu this way, but the install of the retinaface package is unsuccessful.
(Could not find a version that satisfies the requirement tensorflow==2.1.0)
Any ides or suggestion?
Thanks!
