### ISSUE TITLE
DeepFace.verify does not take list of multiple faces

### ISSUE THREAD

**Issue by dlee0324** [serengil/deepface#257]
I was following the past solution (https://github.com/serengil/deepface/issues/8) to run DeepFace.verify with multiple images, but the code doesn't take a list created with .glob, while it takes a list that is manually created. For example,  the code

`imgfolder = 'names'`
`keywords = 'Test'`
`fn = 'img_1.jpg'`
`otherimg = glob.glob(os.path.join(imgfolder, keywords,"*.jpg"))`
`otherimg.remove(os.path.join(imgfolder, keywords,fn))`
`images = [list(elem) for elem in list(zip(np.repeat(os.path.join(imgfolder, keywords,fn), len(otherimg)), otherimg))]`
`result = DeepFace.verify(images, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')`

generates the following error:
`---------------------------------------------------------------------------`
`IndexError                                Traceback (most recent call last)`
`<ipython-input-126-1b0b025acbcd> in <module>()`
`      8 print(images)`
`      9 `
`---> 10 result = DeepFace.verify(images, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')`

`3 frames`
`/usr/local/lib/python3.7/dist-packages/deepface/commons/functions.py in detect_face(img, detector_backend, grayscale, enforce_detection, align)`
`     90 def detect_face(img, detector_backend = 'retinaface', grayscale = False, enforce_detection = True, align = True):`
`     91 `
`---> 92         img_region = [0, 0, img.shape[0], img.shape[1]]`
`     93 `
`     94         #if functions.preproces_face is called directly, then face_detector global variable might not been initialized.`

`IndexError: tuple index out of range`

while the code

`dataset = [
   ['names/Test/img_1.jpg', 'names/Test/img_0.jpg'], 
   ['names/Test/img_1.jpg', 'names/Test/img_2.jpg'], 
   ['names/Test/img_1.jpg', 'names/Test/img_3.jpg']  
]`
`result = DeepFace.verify(dataset, enforce_detection=False, model_name='OpenFace', distance_metric='euclidean_l2')
print(result)`

runs successfully.  The two lists "images" and "datasets" are identical as 'images == dataset' generates 'True'.  Any idea why the first one fails, and is there a way around it?

**Comment by serengil** [comment]
This is because of join function uses seperator in the wrong direction.

Running with otherimg = glob.glob(os.path.join(imgfolder, keywords,"*.jpg"))

[['deepface/tests/dataset\\img1.jpg', 'deepface/tests/dataset\\img10.jpg'], ['deepface/tests/dataset\\img1.jpg', 'deepface/tests/dataset\\img11.jpg'], ['deepface/tests/dataset\\img1.jpg', 'deepface/tests/dataset\\img12.jpg'], ['deepface/tests/dataset\\img1.jpg', 'deepface/tests/dataset\\img13.jpg'], ['deepface/tests/dataset\\img1.jpg', 'deepface/tests/dataset\\img14.jpg']]

Expected

[['deepface/tests/dataset/img1.jpg', 'deepface/tests/dataset/img10.jpg'], ['deepface/tests/dataset/img1.jpg', 'deepface/tests/dataset/img11.jpg'], ['deepface/tests/dataset/img1.jpg', 'deepface/tests/dataset/img12.jpg'], ['deepface/tests/dataset/img1.jpg', 'deepface/tests/dataset/img13.jpg'], ['deepface/tests/dataset/img1.jpg', 'deepface/tests/dataset/img14.jpg']]

As seen terms \\ should be / instead

**Comment by dlee0324** [comment]
Thanks for the response. But the code still encounters the same error. Specifically,

1) I'm running this on google colab, and a print out of **otherimg** gives paths with '/', not '\'.
2) Even after I manually replace the (presumable) '\\' with '/' using `str.replace()`, it still generates the same error.
3) I changed the %cd with `os.chdir()`  in order to avoid the slash concerns, which generates the following list:
`[['img_1.jpg', 'img_0.jpg'],  ['img_1.jpg', 'img_2.jpg'],   ['img_1.jpg', 'img_3.jpg']]`
Running `DeepFace.verify()` with this list still generates the same error. So it doesn't seem like the issue comes from the slashes. Again, when I manually create the list myself as below, the `DeepFace.verify()` runs successfully:
`dataset1 = [['img_1.jpg', 'img_0.jpg'], ['img_1.jpg', 'img_2.jpg'], ['img_1.jpg', 'img_3.jpg']]`

This might be a google colab issue but I can't seem to figure this out ... if you have any tips/suggestions that'd be much appreciated!
