### ISSUE TITLE
bad results with facenet 512

### ISSUE THREAD

**Issue by sadimoodi** [serengil/deepface#287]
I have been experimenting with the facenet 512 model that you just released and getting pretty bad results compared to the 128 model, here is what I did to try solving the problem:
1- did not use Cosine, instead used "euclidean" and "euclidean_l2", it seems like euclidean_l2 is the best distance measure but not as good as the euclidean_l2 running on the facenet 128 model as i am getting lots of False Positives. The euclidean_l2 and euclidean distance of the same face (using different images) is very close to different photos of different persons (when running deepface.verify) hence resulting in more FPs, I am aware of your threshold optimization method that you posted on your blog, but this is not going to solve the problem since the distance calculated between two images of the same person is VERY close to the images that belong to different persons.
Look here:

['database\\George Clony/img39.jpg' **19.81332**]
Threshold =  23.564685968740186
wrong prediction, Label = img
['database\\Ali Khankan/My Photo.jpg' **19.596684**]
Threshold =  23.564685968740186
My Photo

2- changed the normalization function to img = (img - 127.5) /128 as suggested by other people instead of only dividing by 255 as you did, the results improved but not as good as facenet 128

It seems pretty odd to get worse results on the 512 model compared with the 128 as we are gathering more features from the image so this should result in higher accuracy when measuring distance.

**Comment by serengil** [comment]
Facenet128 got [99.2%](https://github.com/davidsandberg/facenet/tree/15839c8d730660eacad35ca267938834fdbe3403) whereas Facenet512 got [99.65%](https://github.com/davidsandberg/facenet/wiki/Training-using-the-VGGFace2-dataset) accuracy on LFW as its creator mentioned.

In my experiment, euclidean and l2 got 99% and cosine got 97% accuracy based on these pairs: https://github.com/serengil/deepface/blob/master/tests/dataset/master.csv

It seems that the higher dimensions does not mean higher score!

I am going to close this issue if it is oke, because deepface wrapped pre-trained facenet model and here we discuss the performance of this pre-trained model.
