### ISSUE TITLE
Face Detection Problem

### ISSUE THREAD

**Issue by bharatsood10** [serengil/deepface#29]
I have tested your Deepface Library with a lot of images and it outperforms well... but there is a issue in face detection.. Sometime's Face not got detected in image and it returns valueError. So to make sure faces should be detected in every image Use MTCNN Library. It detects every faces in images. Its Far better than haar cascade in opencv. let me know your suggestion...

Thanks

**Comment by serengil** [comment]
I will study on MTCNN, that would be my homework. However, as you mentioned that is because of opencv. I will close this issue because it is not directly related to deepface.

You can set enforce_detection argument to false when calling verify or analyze function if you do not want to get error when face is not deteceted.

**Comment by serengil** [comment]
DeepFace started to wrap different backends such as OpenCV, SSD, Dlib and MTCNN to handle those early stages in its newly released version
