### ISSUE TITLE
Why do we use freeze-frame and how can I stop it.

### ISSUE THREAD

**Issue by blueprintparadise** [serengil/deepface#335]
Hi Serengil, Love your code and thank you so much for providing such extensive documentation, you are truly a life-saver.
I was wondering why the frame freezes had to be added, can we not just have a smooth live stream and the system in the back taking images from the feed , analyzing them and printing the name onto the screen ? Please let me know if such a feature is possible, if yes I would love to try my hand at making it and adding it to the project.
Thank You

**Comment by serengil** [comment]
that is because of to disable waitings when your hardware processing. unfortunately, cpus cannot do facial recognition tasks in milliseconds.

stream function expects time_threshold and frame_threshold arguments as inputs optionally. you can configure this waiting time with those arguments. Try to set them to 1.

contributions are of course welcome!
