### ISSUE TITLE
Analyze with numpy input.

### ISSUE THREAD

**Issue by PankajSavaliya** [serengil/deepface#380]
```
img = BytesIO(requests.get(image.url).content)
frame_byte = bytearray(urllib.request.urlopen(data.image.url).read())
np_array = numpy.asarray(frame_byte, dtype=numpy.uint8)
frame = cv2.imdecode(np_array,
                     cv2.IMREAD_UNCHANGED)  # 'Load it as it is'

print(np_array, type(np_array))  # type is numpy.ndarray
print(frame, type(frame))  # type is numpy.ndarray

obj = DeepFace.analyze(img_path=np_array, actions=['age', 'gender', ],
                       enforce_detection=False)
```
both output types are numpy.ndarray and np_array getting an error and the second one getting the right result, can you please explain why the first one is not working even it's the right type for method?.

**Comment by FranSPG** [comment]
If i reproduced exactly the error you got, I think that the problem here is even though they are both NumPy ndarray, their shapes are not equals, you can see this with `np_array.shape` and `frame.shape`.

![Screen Shot 2021-12-07 at 10 44 14](https://user-images.githubusercontent.com/24665960/145040142-c3aaafbf-2cb9-49cb-94bb-e0b8ee0627bd.png)


You need to process the binary as an image and that's the job that you're doing in the line 

`frame = cv2.imdecode(np_array, cv2.IMREAD_UNCHANGED)  # 'Load it as it is'.`

If this doesn't solve your error, please provide more information about the error and maybe I could help you.
