### ISSUE TITLE
Multi-Thread

### ISSUE THREAD

**Issue by LOANPIA** [serengil/deepface#509]
I want to ask you about DeepFace library could be optimize multiple thread?
My CPU: 
![image](https://user-images.githubusercontent.com/67187484/178921396-d43395ef-46bc-48e7-84c0-9d1e9765e933.png)

I gonna build Virtual Machine like 4cpu, 3.6GHz/CPU. Is this a reasonable choice?

**Comment by serengil** [comment]
the answer is yes and no

in my experiments, i cannot run many deepface threads in parallel because tensorflow object cannot be moved among threads. meanwhile, if you are going to run its api, you can have many workers with gunicorn.

btw, even if you run it in single thread, tensorflow uses all your cpu cores. so, it is already in parallel!

**Comment by LOANPIA** [comment]
I got nice answer, thank you Mr.Sefik!

**Comment by lounging-lizard** [comment]
@serengil (excuse my ignorance) but is it that case that calling `DeepFace.represent` in seperate threads is unsafe?
