### ISSUE TITLE
DeepFace.find and DeepFace.analyze issues 

### ISSUE THREAD

**Issue by pengKiina** [serengil/deepface#51]
```
import pandas as pd
df=DeepFace.find(img_path='dataset/peng.png',db_path='C:/R_Py/Jupyter/deepface/dataset')
```

Using VGG-Face model backend and cosine distance.

Analyzing:   0%|                                                                                 | 0/1 [00:00<?, ?it/s]

WARNING: Representations for images in  C:/R_Py/Jupyter/deepface/dataset  folder were previously stored in  representations_vgg_face.pkl . If you added new instances after this file creation, then please delete this file and call find function again. It will create it again.
There are  4  representations found in  representations_vgg_face.pkl

Analyzing: 100%|█████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.71it/s]

find function lasts  1.724104881286621  seconds

`df.shape[0]`
0

Hi Selfk,

1. When I tried the DeepFace.find with datasets, it shows no time in the data frame. 

2. It is not possible to delete it says the pkl is used in python(If you added new instances after this file creation, then please delete this file and call find function again. It will create it again. )

3, when I run the DeepFace.analyze, there are some detection are not accurate at all, man becomes women, kids are 26 years old, is there any way to retrain or get the result correctly? the easier the better, I am a beginner of the deepface. 

Please kindly help with the 3 issues. 

Thanks a lot!

Peng from youtube

``

**Comment by serengil** [comment]
Hello,

Firstly, shape of the data frame is 0 because it cannot find any items similar to peng.png

1- You fed an item and it is completed in 2.71 seconds. That demonstration comes from tqdm library. On the other hand, if you feed multiple items then this progress bar will be meaningful.

```
test_set = ['dataset/peng.png', 'dataset/peng2.png', 'dataset/peng3.png']
dfs = DeepFace.find(test_set, db_path='C:/R_Py/Jupyter/deepface/dataset')
print(dfs) #this is a list of pandas data frames
```

2- This is just warning. People might add new items in that folder but if they would not delete .pkl file, then framework will not process new items. This warning message aims to avoid this.

3- Age and gender prediction study is mainly based on this tutorial: https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/

Age can be predicted  ± 4.65 years whereas gender can be predicted 96.29% accuracy. But I know there are limited instances for kids in the trainset. You can re-train the model if you have a larger data set but I used the combination of wikipedia and imdb data set and it is very large data set. You can find the deeply explanation of the data set as well in the tutorial I shared.
