### ISSUE TITLE
Support prebuilt detectors as input in deepface's verify method

### ISSUE THREAD

**Issue by PulkitMishra** [serengil/deepface#573]
Hi @serengil thanks for open sourcing this library. From what I understand it is possible to use build_model and pass it to deepface.verify but the same is not supported for detector_backend. It would be really great if we can also pass prebuilt detctor inside deepface verify.
I could work on this if this is a change you would like to see. Thanks again!

**Comment by serengil** [comment]
verification function supports this because in initial versions library loads the model again and again. now, if it is loaded once, library will use the pre-loaded one. so, passing pre-trained model is not important anymore.

similarly, library builds face detector model once and use it in later calls. you should not focus on this.

**Comment by PulkitMishra** [comment]
thanks for the quick response @serengil . really appreciate it. but then if I create a rest api, will the detector not be build two times for 2 separate calls?

**Comment by serengil** [comment]
no, it will build a face detector model in 1st call, and this is going to be used in other calls.
