### ISSUE TITLE
Batch Predictions

### ISSUE THREAD

**Issue by swapnika92** [serengil/deepface#678]
How can we get facial attributes (gender, age, etc.) for multiple images (BATCH PREDICTIONs)?
Currently, "analyze" function builds the model when run for each image individually - leading to longer processing time.

**Comment by serengil** [comment]
you should call the function in a for loop. ml models built with singleton pattern. so, you do not spend time to re-built model in that loop.

**Comment by milesmcc** [comment]
@serengil would it be possible to extend the library to support batch inference when running on GPUs? While the ML model has a singleton pattern and so it isn't re-built each call, it would be helpful to have a method to truly parallelize inference.

If you think this is possible, I'm happy to try and submit a PR myself or pay a bounty to the person who does (though it'd need to be small because I don't have much money haha).
