### ISSUE TITLE
deepface model

### ISSUE THREAD

**Issue by YasserSyr** [serengil/deepface#7]
I take the FBdeepface.py file and download VGGFace2_DeepFace_weights_val-0.9034.h5.zip model. I implemented it in my code. 
I am working on the face recognition system. I use your model to predict face.
Is it normal to take 50 seconds to predict?

- Keeping in mind the dataset I used  contains 450 images(10 people)

**Comment by serengil** [comment]
Yes, this is normal because deepface is very complex model. It has 120M params. You might switch to OpenFace if you do not have a strong computer or real time demand. OpenFace just has 3M params.

BTW, You can find the comparison of these models here: https://sefiks.com/2020/02/17/face-recognition-with-facebook-deepface-in-keras/
