### ISSUE TITLE
Each time ram usage getting larger

### ISSUE THREAD

**Issue by pasa13142** [serengil/deepface#78]
After each ram usage getting larger even i changed the loading models to once. for example models get started with 6 gb ram usage, then one analyse query, it is 8.51 gb now. then another query, it is 8.55 gb now. How can i stop it ? 

Bir de türkçe açıklamak isterim açıkcası. Bir servis yazıyorum ve modeli deepface içindeki gibi her seferinde baştan yüklemek maliyetli ve süre alan bir işlem oluyordu. Modeli yukarı tek seferlik yüklenicek sekilde aldım, süre epey bir azaldı fakat ram şişme sorunu hala devam ediyorum. Herhangi bir fikriniz var mıdır acaba ?

**Comment by barathraj2612** [comment]
even i have the same problem its using my 12 gb ram and even my swap of ubuntu

**Comment by serengil** [comment]
Do not use nested for loops when calling deepface functions. Instead of this, you should pass inputs as array as shown below. 

`results = DeepFace.verify([['img1.jpg', 'img2.jpg'], ['img1.jpg', 'img3.jpg']])`

On the other hand, if you really need to call deepface with for loops you can call keras clear_session function in some iterations (e.g. each 5th iteration)
