### ISSUE TITLE
[Proposal] Rewrite Deepface to PyTorch

### ISSUE THREAD

**Issue by alyxdow** [serengil/deepface#781]
I'm propose to to rewrite Deepface to PyTorch, and can help & sponsor this.

**Comment by serengil** [comment]
I am fully satisfied with tensorflow, why would i want to seitch pytorch?

**Comment by alyxdow** [comment]
Backend-level, it will be good for production.

**Comment by serengil** [comment]
disagree. deepface will be based on tf.

**Comment by Khaled-Fawry** [comment]
Currently, TensorFlow doesn't work on Nvidia RTX 5xxx Series cards (Compute Capability 12). I had to stop using DeepFace even though I liked it because I simply cannot run the models on my gpu.

No one is demanding anything here, we're more than grateful for this cool software, I'm just clarifying why PyTorch would be better, Also PyTorch supports Intel GPUs which TF doesn't.

**Comment by ki321g** [comment]
I manged to get DeepFace working completely on a Raspberry Pi 5 Project for Facial recognition. I didnt use a GPU at all i set it up to use the CPU and it worked great

**Comment by Khaled-Fawry** [comment]
> I manged to get DeepFace working completely on a Raspberry Pi 5 Project for Facial recognition. I didnt use a GPU at all i set it up to use the CPU and it worked great

Great! but how's that related to our conversation? it's good that you didn't need a GPU but if you're using heavy models like Retina Face in a more complex system, you will have hard time without a GPU.
