### ISSUE TITLE
Input as a numpy array or a list of numpy arrays to DeepFace functions

### ISSUE THREAD

**Issue by rajmuchhala** [serengil/deepface#84]
Hi, I just wanted to know 
1. If there is any way we can input a numpy array or a list of numpy arrays to find() and analyze() functions instead of the image paths?
2. Also in stream() function, can you also enable the option of input as a video file like mp4,avi, etc. along with webcam?

**Comment by serengil** [comment]
1- yes you can pass numpy array or base64 encoded image instead of exact path. 

This is handled in [functions.py](https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py), 173th line:

```
if type(img).__module__ == np.__name__:
   exact_image = True
```

2- I'll add video streaming feature in the next release.

This is handled in [realtime.py](https://github.com/serengil/deepface/blob/master/deepface/commons/realtime.py), 144th line:

```
cap = cv2.VideoCapture(0) #webcam
#cap = cv2.VideoCapture("C:/Users/IS96273/Desktop/skype-video-1.mp4") #video
```

As seen, if you pass video path instead of 0, then it will process video instead of web cam.
