### ISSUE TITLE
local weights not used keeps downloading

### ISSUE THREAD

**Issue by noparadigm** [serengil/deepface#849]
I have downloaded the weights from https://github.com/serengil/deepface_models/releases and placed them in /home/usrprj/.deepface/weights/ but it keeps downloading them where is the correct location ?

**Comment by serengil** [comment]
Your directory seems correct. For instance, my weights are stored in `~/.deepface/weights`

If you have DEEPFACE_HOME environment variable, then it would use that instead of home directory as coded [here](https://github.com/serengil/deepface/blob/master/deepface/commons/functions.py#L57).

When it attempts to download, what is the location?

**Comment by noparadigm** [comment]
I have set the DEEPFACE_HOME environment variable and the weights are download is displayed can this be suppressed ?

**Comment by serengil** [comment]
no, gdown will display progress for downloading by default
