### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by BasilBeirouti** [serengil/deepface#890]
AttributeError: 'NoneType' object has no attribute 'shape'

```
$ df = DeepFace.find(img_path="resources/face.jpeg", db_path="resources/dir_001", enforce_detection=False)

Finding representations:   0%|▎                                                                                                | 247/77736 [00:51<4:28:42,  4.81it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 df = DeepFace.find(img_path="resources/face.jpeg", db_path="resources/dir_001", enforce_detection=False)

File ~/.pyenv/versions/3.11.3/envs/cse/lib/python3.11/site-packages/deepface/DeepFace.py:488, in find(img_path, db_path, model_name, distance_metric, enforce_detection, detector_backend, align, normalization, silent)
    485 for index in pbar:
    486     employee = employees[index]
--> 488     img_objs = functions.extract_faces(
    489         img=employee,
    490         target_size=target_size,
    491         detector_backend=detector_backend,
    492         grayscale=False,
    493         enforce_detection=enforce_detection,
    494         align=align,
    495     )
    497     for img_content, _, _ in img_objs:
    498         embedding_obj = represent(
    499             img_path=img_content,
    500             model_name=model_name,
   (...)
    504             normalization=normalization,
    505         )

File ~/.pyenv/versions/3.11.3/envs/cse/lib/python3.11/site-packages/deepface/commons/functions.py:105, in extract_faces(img, target_size, detector_backend, grayscale, enforce_detection, align)
    103 # img might be path, base64 or numpy array. Convert it to numpy whatever it is.
    104 img = load_image(img)
--> 105 img_region = [0, 0, img.shape[1], img.shape[0]]
    107 if detector_backend == "skip":
    108     face_objs = [(img, img_region, 0)]

AttributeError: 'NoneType' object has no attribute 'shape'
```

I'm guessing cv2.imdecode can return None:
https://github.com/serengil/deepface/blob/99f5295638038cf554149edad450e4141583c807/deepface/commons/functions.py#L112

And then when we try to index that img object it throws the attribute error

**Comment by ekkolon** [comment]
Possible duplicate: #768

I don't think this is a bug per se, but the error message could/should definitely be improved.

Most likely the path to the image does not exist or cv2 cannot decode the file's content.

**Comment by serengil** [comment]
still, we have to check img is none and throw a legible message.

**Comment by ekkolon** [comment]
Agreed, working on it.

### A few notes upfront about the refactoring
*Feel free to chime in*

- We need to check for empty image data beforehand, so the downstream `NoneType` error likely occurs here already:
  https://github.com/serengil/deepface/blob/99f5295638038cf554149edad450e4141583c807/deepface/commons/functions.py#L111
  
  _However, this exception is uncaught right now_.

- We don't care about the specific execptions thrown by `cv2` at:
  https://github.com/serengil/deepface/blob/99f5295638038cf554149edad450e4141583c807/deepface/commons/functions.py#L112

  But we should **consider all failed decoding attempts to have occured because the file's content is corrupt**, in that it either contains invalid pixel data or is empty. We can omit the latter because we should have handled this based on the above steps.

**Comment by serengil** [comment]
We started to use imread again and throw exception if file name has non-english character with PR - https://github.com/serengil/deepface/pull/911
