### ISSUE TITLE
enforce detection parameter

### ISSUE THREAD

**Issue by YCAyca** [serengil/deepface#95]
Hi,
I try to understand and compare the performation of the models on different metrics. Can you tell me what is the enforce_detection parameter and why it has a value as "True"

**Comment by serengil** [comment]
A modern face recognition pipeline consists of 4 common stages: detect, align, represent and verify. Here, detection and alignment are not must but enabling those stages increases the model accuracy dramatically. Google declared the just alignment increases 1%  accuracy. That's why, deepface expects to detect and align faces in the preprocessing.

If your input images are not high resolution, then face detection and alignment cannot be handled. If you still want to apply face recognition, you should set enforce_detection to False. 

Its default value is True. If it cannot detect a face in a fed image, then it returns an exception "Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False." throwed by commons/functions.py
